name: exmachina-fanfiction
favicon: null
layout_spectrum: 0.36659
typography_spectrum: 0.24054
title: 'Ex Machina: The fan-made Novel'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dd4446'
    - '#6d4445'
    - '#fefefe'
    - '#434242'
    - '#978888'
  brandStrength: 0.8125
  lightness: 0.4375
  saturation: 0.9375
  rhythmicContrast: 1
purpose: []
