typography_spectrum: 0.24054
color:
  brandColors:
    - '#ebf2f8'
    - '#e3ac76'
    - '#6fc0d1'
    - '#da6a52'
    - '#008ca7'
  brandStrength: 0.4375
  lightness: 0.375
  saturation: 0.1875
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.33784
analytics:
  google: null
  facebook: null
  twitter: null
name: exmachina-fanfiction
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Ex Machina for the fan-made Novel
purpose: []
