name: exmachina-fanfiction
favicon: null
layout_spectrum: 0.13225
typography_spectrum: 0.24054
title: 'Ex Machina: The fan-made Novel'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebf2f8'
    - '#e3ac76'
    - '#6fc0d1'
    - '#da6a52'
    - '#008ca7'
  brandStrength: 0.25
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
