name: exmachina-fanfiction
favicon: null
layout_spectrum: 0.27111
typography_spectrum: 0.24054
title: 'Ex Machina: The fan-made Novel'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#404040'
    - '#7c898f'
    - '#57646b'
    - '#a3afb3'
  brandStrength: 0.0625
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
