name: exmachina-fanfiction
favicon: null
layout_spectrum: 0.6429
typography_spectrum: 0.24054
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.375
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
