name: exmachina-fanfiction
favicon: null
layout_spectrum: 0.36834
typography_spectrum: 0.24054
title: Ex Machina for the fan-made Novel
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#ef2e31'
    - '#ffffff'
    - '#efa6a0'
    - '#4c4c4c'
  brandStrength: 0
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
