typography_spectrum: 0.24054
color:
  brandColors:
    - '#051717'
    - '#d3f1d2'
    - '#166154'
    - '#55a0a5'
    - '#e47095'
  brandStrength: 0
  lightness: 0.125
  saturation: 1
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.36659
analytics:
  google: null
  facebook: null
  twitter: null
name: exmachina-fanfiction
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: The Fan-Made Novel
purpose: []
