name: exmachina-fanfiction
favicon: null
layout_spectrum: 0.5831
typography_spectrum: 0.24054
title: 'Ex Machina: The fan-made Novel'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#9b4e30'
    - '#2db99f'
    - '#8e0c64'
    - '#a5cdcd'
  brandStrength: 0.0625
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
